# Generated by Django 3.1.7 on 2021-04-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
